; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Menu Tray, Icon, C:\Users\WhoAmI\Downloads\Red_chinchompa_detail.ico

Gui -MinimizeBox -MaximizeBox
Gui Color, 0xC46200
Gui Font, s9, Trebuchet MS
Gui Add, Text, x8 y24 w152 h23 +0x200, Average Caught to Logout:
Gui Font
Gui Add, Edit, vLogoutRandomInput x160 y24 w54 h21 +Number, 1
Gui Font, s9, Trebuchet MS
Gui Add, Text, x8 y48 w242 h23 +0x200, Minutes to spend logged out: (Min to Max)
Gui Font
Gui Add, Edit, vMinLogoutTimeInput x248 y48 w28 h22 +Number, 1
Gui Font, s9, Trebuchet MS
Gui Add, Text, x280 y48 w11 h22 +0x200 +Center, to
Gui Font
Gui Add, Edit, vMaxLogoutTimeInput x296 y48 w28 h22 +Number, 1
Gui Font, s12 Italic, Trebuchet MS
Gui Add, Text, x8 y0 w120 h23 +0x200, Logout Settings
Gui Font
Gui Add, Button, x8 y80 w108 h28 gStartScript, Start
Gui Add, Button, x216 y80 w108 h28 gCancelScript, Exit
Gui Show, w332 h116, Red Chin Catcher V3
Return

GuiClose:
    ExitApp

StartScript:
GUI, Submit
Run, "%A_ScriptDir%\Red Chin Script V3.ahk"
ExitApp

CancelScript:
ExitApp