; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Menu Tray, Icon, shell32.dll, 42

Gui -MinimizeBox -MaximizeBox +AlwaysOnTop
Gui Add, Button, x79 y56 w116 h32, Start
Gui Add, DropDownList, x8 y24 w120, Food||Guthans|Foodless
Gui Font, s10 q4, Calibri
Gui Add, Text, x8 y0 w120 h23 +0x200, Select Healing Type
Gui Add, CheckBox, x144 y0 w121 h23, Enable Potions
Gui Add, CheckBox, x144 y24 w125 h23, Enable Drop Pickup

Gui Show, w274 h98, AIO Fighter Options
Return

GuiEscape:
GuiClose:
ExitApp